import assert from 'node:assert/strict';
import {BrowserTimeoutAlerts,createTimeoutNotification} from '../src/lib/veto/browserTimeoutAlerts.ts';
let now=1000,permission='default',sounds=0;const storage=new Map(),notifications=[];
const port={permission:()=>permission,now:()=>now,read:key=>storage.get(key)||null,write:(key,value)=>storage.set(key,value),play:()=>sounds++,show:(item,reminder)=>{const notice={item,reminder,closed:false,close(){this.closed=true;}};notifications.push(notice);return notice;}};
const item={id:'report-1',matchId:'match-1',teamA:'Alpha',teamB:'Beta',requestedBy:'Alpha'};
const first=new BrowserTimeoutAlerts(port),otherTab=new BrowserTimeoutAlerts(port);
first.sync([item]);assert.equal(notifications.length,0);
permission='denied';first.sync([item]);assert.equal(notifications.length,0);
permission='granted';first.sync([item]);assert.equal(notifications.length,1);assert.equal(sounds,1);assert.equal(notifications[0].reminder,false);
otherTab.sync([item]);first.sync([item]);assert.equal(notifications.length,1);
now+=29999;first.sync([item]);assert.equal(notifications.length,1);
now++;first.sync([item]);assert.equal(notifications.length,2);assert.equal(notifications[0].closed,true);assert.equal(notifications[1].reminder,true);assert.equal(sounds,2);
otherTab.sync([item]);assert.equal(notifications.length,2);
first.sync([]);assert.equal(notifications[1].closed,true);now+=60000;first.sync([]);assert.equal(notifications.length,2);
first.sync([{...item,id:'report-2'}]);assert.equal(notifications.length,3);permission='denied';first.sync([{...item,id:'report-2'}]);assert.equal(notifications[2].closed,true);
permission='granted';const privateMode=new BrowserTimeoutAlerts({...port,read(){throw Error('Blocked storage');},write(){throw Error('Blocked storage');}});
privateMode.sync([item]);privateMode.sync([item]);assert.equal(notifications.length,4);privateMode.dispose();assert.equal(notifications[3].closed,true);
const unavailable=new BrowserTimeoutAlerts({...port,show(){throw Error('Unsupported notification constructor');}});assert.doesNotThrow(()=>unavailable.sync([item]));
first.dispose();otherTab.dispose();
let clicked=null,closed=false;const native={onclick:null,onerror:null,close(){closed=true;}};
createTimeoutNotification(item,false,request=>{clicked=request;},(title,options)=>{assert.equal(title,'Timeout requested: Alpha');assert.equal(options.requireInteraction,true);assert.equal(options.renotify,true);assert.equal(options.silent,false);assert.equal(options.tag,'veto-timeout:report-1');assert.match(options.body,/Alpha vs Beta/);return native;});
native.onclick();assert.equal(clicked,item);assert.equal(closed,true);
console.log('PASS browser timeout alerts: permission gate, immediate alert, 30-second audible reminders, cross-tab deduplication, resolution closes/stops, private storage and unsupported browser recovery');
